#!/usr/bin/env bash
# Installs a nginx server and sets  301 Moved Permanently
./1-install_nginx_web_server
redirect="location /redirect_me {\nrewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n}\n"
sudo sed -i "30i $redirect" /etc/nginx/sites-available/default
service nginx restart
