#!/usr/bin/env bash
# Installs a nginx server and sets  301 Moved Permanently
./1-install_nginx_web_server
replace="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "29i $replace" /etc/nginx/sites-available/default
service nginx restart
