#!/usr/bin/env bash
# Installs a nginx server and sets  301 Moved Permanently
./1-install_nginx_web_server
redirect="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "19i $redirect" /etc/nginx/sites-available/default
service nginx restart
