#!/usr/bin/env bash
# Configure the 404 page
./3-redirection
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i '30 i\ \terror_page 404 /404.html;\nlocation = /404.html {root /var/www/html;internal;}' /etc/nginx/sites-enabled/default 
service nginx restart
