#!/usr/bin/env bash
# Install HAProxy with round robin balancing algorithm
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get install haproxy
sed -i "20 i\ \n\tfrontend haproxynode\n\t\tbind *:80\n\t\tmode http\n\t\tdefault_backend backendnodes\n\tbackend backendnodes\n\t\tbalance roundrobin\n\t\tmode http\n\t\tserver 1072-web-01 34.73.110.76\n\t\tserver 1072-web-02 34.228.145.214\n" /etc/haproxy/haproxy.cfg
service haproxy restart
