#!/usr/bin/env bash
# Displays Holberton 10 times, but "good luck" for 8th iteration, and "bad luck" for 4th iteration
i=0
while [ $i -lt 10 ]
do	
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((++i))
done
