#!/usr/bin/env bash
# Display numbers from 1 - 20 and bad luck
i=1
while [ $i -lt 21 ]
do
    echo $i
    case $i in
        3)
            echo "bad luck from China"
            ;;
        8)
            echo "bad luck from Japan"
            ;;
        16)
            echo "bad luck from Italy"
            ;;
    esac
    ((i++))
done
