#!/usr/bin/env bash
# Tests if a file is empty or not
file="holbertonschool"
if [ -e $file ]
then
	echo "holbertonschool file exists"
	if [ -s $file ]
	then
		echo "holbertonschool file is not empty"
	else
		echo holbertonschool file is empty
	fi
	if [ -f $file ]
	then
		echo holbertonschool is a regular file
	fi
else
        echo "holbertonschool file dose not exist"
fi
